### ISSUE TITLE
Info symbolic image broken on Librem 5

### ISSUE THREAD

**Issue by baarkerlounger** [pablo-s/passes#31]
Device Librem 5 
PureOS Byzantium (Debian Bullseye based)

Passes installed via Flathub Flatpak.

When you open a pass, the info button has a broken image link as if the svg at `data/icons/hicolor/scalable/actions/info-symbolic.svg` has not installed properly. This does not seem to be reproducible when installing on x86.

**Comment by pablo-s** [comment]
Hi @baarkerlounger ! Thanks for reporting this issue!

I am not sure what the problem is and how to reproduce it. In both my laptop and my Pinephone (running postmarketOS) the application behaves in the exact same way. And in both I can see all icons correctly.

Can you see correctly the qr-code icon?

**Comment by baarkerlounger** [comment]
@pablo-s yes the QR code icon shows fine

**Comment by pablo-s** [comment]
Hi @baarkerlounger ! I think I have to say sorry because I should have know what was happening :'(

For different reasons I have not had time to release a new version of Passes. Because of that, I have been accumulating many improvements and fixes in the main branch for months.

One of these fixes is 4bcda09, that includes the icon that you are expecting to see...

The good news is that I have released a new version of Passes today! When you have time, update and let me know if it works! :)

**Comment by baarkerlounger** [comment]
Yes works now. Thank you very much.
